---

- name: main | daemon sshd customs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: 'sshd_config.j2',   dest: '/etc/ssh/sshd_config'}
  notify:
    - restart sshd