---
docker_registry: '<<IP_PRIVATE_KASSA_REGISTRY>>'
ssh:
  authmethods: 'publickey'
  pwdauth: 'no'
  permitrootlogin: 'no'
  list_users_with_ip: 'samodelkin alex@127.0.0.1 alex@127.0.0.2 denys@127.0.0.3 denys@127.0.0.4'