---
docker_registry: '<<IP_PRIVATE_KASSA_REGISTRY>>'
ssh:
  authmethods: 'publickey'
  pwdauth: 'no'
  permitrootlogin: 'no'
  list_users_with_ip: 'alex@127.0.0.1 alex@127.0.0.2 denys@127.0.0.3 denys@127.0.0.4'
web:
  dir: '/var/www'
  url_to_get_ips: 'https://www.cloudflare.com/ips-v4'
php:
  image: 'php:7.4-fpm'
  upload_max_filesize: '20m'
  post_max_size: '20m'
  timezone: 'Europe/Moscow'
  server_name: 'example.com'