---
- name: main | create project dir
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - '{{ web.dir }}'
    - '{{ web.dir }}/example.com'
    - '{{ web.dir }}/images'

- name: main | get_ip_list from https://www.cloudflare.com/ips-v4
  get_url:
    url: "{{ web.url_to_get_ips }}"
    dest: "{{ web.dir }}/ips-v4"
    mode: '0440'

- name: main | template configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: docker-compose.yml.j2,                            dest: "{{ web.dir }}/docker-compose.yml" }
    - { src: Dockerfile.j2,                                    dest: "{{ web.dir }}/images/Dockerfile" }
    - { src: example-com.conf.j2,                              dest: "{{ web.dir }}/example.com/example-com.conf" }
    - { src: kassa.php.j2,                                     dest: "{{ web.dir }}/example.com/kassa.php" }
    - { src: php.ini.j2,                                       dest: "{{ web.dir }}/images/php.ini" }

- name: main | Start kassa
  docker_compose:
    project_src: "{{ web.dir }}"
    restarted: yes




