#######KASSA_STEND_DEMO##########
[all:children]
kassa

[all:vars]
ansible_port=22
# ansible_python_interpreter=/bin/python3

[kassa:children]
demo_php

[demo_php]
kassaphp1    ansible_host=192.168.88.182 # use your address(!!!)